// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxucqufimhnnuebpjsxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dWNxdWZpbWhubnVlYnBqc3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzgyOTUsImV4cCI6MjA1NzkxNDI5NX0.ZBCc3pTEzyitzpPnvFLisBBC1NjOoZJcasfW_i0qFiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);